development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:c802c3c41a89c5090a190c3a87e1ab64@sole.redistogo.com:9728/
  channel_prefix: message_me_production
